<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: DejaVu Sans, sans-serif; font-size:9px; color:#1a1a2e; background:#fff; }

    .header { background:#0047ab; color:#fff; padding:14px 20px; }
    .header table { width:100%; border-collapse:collapse; }
    .header td { vertical-align:middle; }
    .header .title { font-size:16px; font-weight:bold; }
    .header .sub   { font-size:9px; opacity:.8; margin-top:2px; }
    .header .meta  { text-align:right; font-size:8px; opacity:.85; line-height:1.7; }

    .section { padding:12px 20px 6px; }
    .section-title { font-size:10px; font-weight:bold; color:#0047ab; border-bottom:1.5px solid #0047ab; padding-bottom:3px; margin-bottom:8px; text-transform:uppercase; letter-spacing:.5px; }

    .info-bar { background:#f0f4ff; border-bottom:1px solid #d0d9f0; padding:8px 20px; font-size:8.5px; }
    .info-bar table { width:100%; border-collapse:collapse; }
    .info-bar td { padding:0 12px 0 0; color:#444; }

    .cards-table { width:100%; border-collapse:collapse; margin-bottom:4px; }
    .cards-table td { width:16.66%; padding:3px; }
    .card-box { background:#f8faff; border:1px solid #e0e7ff; border-radius:5px; padding:8px 10px; }
    .card-box .num { font-size:15px; font-weight:bold; color:#0047ab; }
    .card-box .lbl { font-size:7.5px; color:#666; margin-top:1px; }

    .data-table { width:100%; border-collapse:collapse; font-size:8.5px; }
    .data-table th { background:#0047ab; color:#fff; padding:5px 8px; text-align:left; font-size:8px; font-weight:600; }
    .data-table td { padding:5px 8px; border-bottom:1px solid #f0f0f0; vertical-align:middle; }
    .data-table tr:nth-child(even) td { background:#f8faff; }

    .badge { display:inline-block; padding:2px 6px; border-radius:10px; font-size:7.5px; font-weight:600; }
    .badge-success { background:#e8f5e9; color:#2e7d32; }
    .badge-warning { background:#fff8e1; color:#f57f17; }
    .badge-error   { background:#fce4ec; color:#c62828; }
    .badge-blue    { background:#e3f2fd; color:#1565c0; }
    .badge-teal    { background:#e0f2f1; color:#00695c; }
    .badge-orange  { background:#fff3e0; color:#e65100; }
    .badge-grey    { background:#f5f5f5; color:#555; }

    .kpi-box { background:#f8faff; border:1px solid #e0e7ff; border-radius:6px; padding:12px 16px; text-align:center; }
    .kpi-rate { font-size:28px; font-weight:bold; }
    .kpi-mini table { width:100%; border-collapse:collapse; margin-top:8px; }
    .kpi-mini td { text-align:center; padding:4px; font-size:8px; border-right:1px solid #e0e7ff; }
    .kpi-mini td:last-child { border-right:none; }

    .bar-wrap { background:#e0e0e0; border-radius:3px; height:7px; margin:6px 0; }
    .bar-fill { border-radius:3px; height:7px; }

    .footer { position:fixed; bottom:0; left:0; right:0; background:#f8faff; border-top:1px solid #d0d9f0; padding:5px 20px; }
    .footer table { width:100%; border-collapse:collapse; }
    .footer td { font-size:7.5px; color:#888; }
    .footer td:last-child { text-align:right; }

    .two-col { width:100%; border-collapse:collapse; }
    .two-col td { vertical-align:top; padding:3px; }
</style>
</head>
<body>

<!-- Header -->
<div class="header">
    <table>
        <tr>
            <td>
                <div class="title">PRISM — {{ $province['name'] ?? 'Province' }} Report</div>
                <div class="sub">Department of Science and Technology — Philippines</div>
            </td>
            <td class="meta">
                Generated by: <strong>{{ $generated_by }}</strong><br>
                Date: <strong>{{ $generated }}</strong>
            </td>
        </tr>
    </table>
</div>

<!-- Province Info -->
<div class="info-bar">
    <table>
        <tr>
            <td><strong>Province:</strong> {{ $province['name'] ?? '—' }}</td>
            <td><strong>Category:</strong> {{ $province['category'] ?? '—' }}</td>
            <td><strong>Director:</strong> {{ $province['director'] ?? '—' }}</td>
            <td><strong>Municipalities:</strong> {{ $province['num_municipalities'] ?? '—' }}</td>
            <td><strong>Cities:</strong> {{ $province['num_cities'] ?? '—' }}</td>
        </tr>
    </table>
</div>

<!-- Summary Cards -->
<div class="section">
    <div class="section-title">Summary</div>
    <table class="cards-table">
        <tr>
            <td><div class="card-box"><div class="num">{{ $user_stats['total'] }}</div><div class="lbl">Total Users</div></div></td>
            <td><div class="card-box"><div class="num">{{ $user_stats['employees'] }}</div><div class="lbl">Employees</div></div></td>
            <td><div class="card-box"><div class="num">{{ $user_stats['permanent'] }}</div><div class="lbl">Permanent</div></div></td>
            <td><div class="card-box"><div class="num">{{ $user_stats['cos'] }}</div><div class="lbl">COS</div></div></td>
            <td><div class="card-box"><div class="num">{{ $user_stats['jo'] }}</div><div class="lbl">Job Order</div></div></td>
            <td><div class="card-box"><div class="num">{{ $user_stats['admins'] }}</div><div class="lbl">Admins</div></div></td>
        </tr>
    </table>
</div>

<!-- Employees + Director KPI side by side -->
<div class="section">
    <table class="two-col">
        <tr>
            <!-- Employee List -->
            <td style="width:65%;">
                <div class="section-title">Employee List</div>
                <table class="data-table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>DOST ID</th>
                            <th>Position</th>
                            <th>Status</th>
                            <th>Yrs</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($employee_list as $i => $e)
                        @php
                            $sc = match($e['status']) { 'permanent' => 'badge-blue', 'cos' => 'badge-teal', 'jo' => 'badge-orange', default => 'badge-grey' };
                            $sl = match($e['status']) { 'permanent' => 'Permanent', 'cos' => 'COS', 'jo' => 'Job Order', default => $e['status'] };
                        @endphp
                        <tr>
                            <td>{{ $i + 1 }}</td>
                            <td><strong>{{ $e['name'] ?: '—' }}</strong></td>
                            <td>{{ $e['dost_id'] }}</td>
                            <td>{{ $e['position'] }}</td>
                            <td><span class="badge {{ $sc }}">{{ $sl }}</span></td>
                            <td>{{ $e['length_of_service'] }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </td>

            <!-- Director KPI -->
            <td style="width:35%; padding-left:12px;">
                <div class="section-title">Director KPI</div>
                @if(!empty($director_kpi) && $director_kpi['total_items'] > 0)
                @php
                    $rate  = $director_kpi['rate'];
                    $color = $rate >= 90 ? '#2e7d32' : ($rate >= 75 ? '#f57f17' : '#c62828');
                @endphp
                <div class="kpi-box">
                    <div class="kpi-rate" style="color:{{ $color }};">{{ $rate }}%</div>
                    <div style="font-size:8px; color:#666; margin-top:2px;">Accomplishment Rate</div>
                    <div class="bar-wrap">
                        <div class="bar-fill" style="width:{{ min($rate, 100) }}%; background:{{ $color }};"></div>
                    </div>
                    <div class="kpi-mini">
                        <table>
                            <tr>
                                <td><strong>{{ $director_kpi['total_items'] }}</strong><br>KPI Items</td>
                                <td><strong style="color:#2e7d32;">{{ $director_kpi['accomplished'] }}</strong><br>Accomplished</td>
                                <td><strong>{{ $director_kpi['target'] }}</strong><br>Target</td>
                            </tr>
                        </table>
                    </div>
                </div>
                @else
                <div style="color:#999; font-size:8px; padding:12px;">No KPI data available.</div>
                @endif
            </td>
        </tr>
    </table>
</div>

<!-- Activity Log Summary -->
<div class="section">
    <div class="section-title">Activity Log Summary</div>
    <table class="cards-table">
        <tr>
            <td><div class="card-box"><div class="num">{{ $log_stats['login'] }}</div><div class="lbl">Logins</div></div></td>
            <td><div class="card-box"><div class="num">{{ $log_stats['create'] }}</div><div class="lbl">Creates</div></div></td>
            <td><div class="card-box"><div class="num">{{ $log_stats['update'] }}</div><div class="lbl">Updates</div></div></td>
            <td><div class="card-box"><div class="num">{{ $log_stats['delete'] }}</div><div class="lbl">Deletes</div></div></td>
            <td><div class="card-box"><div class="num">{{ $log_stats['generate'] }}</div><div class="lbl">Generates</div></div></td>
            <td><div class="card-box"><div class="num">{{ $log_stats['export'] }}</div><div class="lbl">Exports</div></div></td>
        </tr>
    </table>
</div>

<!-- Recent Logs -->
<div class="section">
    <div class="section-title">Recent Activity</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>User</th>
                <th>DOST ID</th>
                <th>Role</th>
                <th>Action</th>
                <th>Description</th>
                <th>Date & Time</th>
            </tr>
        </thead>
        <tbody>
            @foreach($recent_logs as $log)
            @php
                $tc = match($log['type']) {
                    'login','logout' => 'badge-success',
                    'create','update' => 'badge-blue',
                    'delete' => 'badge-error',
                    'generate' => 'badge-teal',
                    'export' => 'badge-grey',
                    default => 'badge-grey',
                };
            @endphp
            <tr>
                <td><strong>{{ $log['name'] ?: '—' }}</strong></td>
                <td>{{ $log['dost_id'] }}</td>
                <td>{{ str_replace('_', ' ', ucfirst($log['role'])) }}</td>
                <td><span class="badge {{ $tc }}">{{ $log['type'] }}</span></td>
                <td>{{ $log['description'] }}</td>
                <td>{{ $log['created_at'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

<!-- Footer -->
<div class="footer">
    <table>
        <tr>
            <td>PRISM — Provincial Director Ranking and Information System for Management</td>
            <td>CONFIDENTIAL — For internal use only</td>
        </tr>
    </table>
</div>

</body>
</html>
