<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: DejaVu Sans, sans-serif; font-size:9px; color:#1a1a2e; background:#fff; }

    /* Header */
    .header { background:#0047ab; color:#fff; padding:14px 20px; }
    .header table { width:100%; border-collapse:collapse; }
    .header td { vertical-align:middle; }
    .header .title { font-size:16px; font-weight:bold; letter-spacing:.5px; }
    .header .sub   { font-size:9px; opacity:.85; margin-top:2px; }
    .header .meta  { text-align:right; font-size:8px; opacity:.85; line-height:1.6; }

    /* Section title */
    .section { padding:14px 20px 6px; }
    .section-title { font-size:10px; font-weight:bold; color:#0047ab; border-bottom:1.5px solid #0047ab; padding-bottom:3px; margin-bottom:8px; text-transform:uppercase; letter-spacing:.5px; }

    /* Stat cards */
    .cards-table { width:100%; border-collapse:collapse; margin-bottom:4px; }
    .cards-table td { width:16.66%; padding:3px; }
    .card-box { background:#f8faff; border:1px solid #e0e7ff; border-radius:5px; padding:8px 10px; }
    .card-box .num  { font-size:15px; font-weight:bold; color:#0047ab; }
    .card-box .lbl  { font-size:7.5px; color:#666; margin-top:1px; }

    /* Tables */
    .data-table { width:100%; border-collapse:collapse; font-size:8.5px; }
    .data-table th { background:#0047ab; color:#fff; padding:5px 8px; text-align:left; font-weight:600; font-size:8px; }
    .data-table td { padding:5px 8px; border-bottom:1px solid #f0f0f0; vertical-align:middle; }
    .data-table tr:nth-child(even) td { background:#f8faff; }

    /* Badges */
    .badge { display:inline-block; padding:2px 6px; border-radius:10px; font-size:7.5px; font-weight:600; }
    .badge-success { background:#e8f5e9; color:#2e7d32; }
    .badge-warning { background:#fff8e1; color:#f57f17; }
    .badge-error   { background:#fce4ec; color:#c62828; }
    .badge-blue    { background:#e3f2fd; color:#1565c0; }
    .badge-teal    { background:#e0f2f1; color:#00695c; }
    .badge-purple  { background:#f3e5f5; color:#6a1b9a; }
    .badge-grey    { background:#f5f5f5; color:#555; }

    /* KPI bar */
    .bar-wrap  { background:#e0e0e0; border-radius:3px; height:6px; width:100%; }
    .bar-fill  { border-radius:3px; height:6px; }

    /* Footer */
    .footer { position:fixed; bottom:0; left:0; right:0; background:#f8faff; border-top:1px solid #d0d9f0; padding:5px 20px; }
    .footer table { width:100%; border-collapse:collapse; }
    .footer td { font-size:7.5px; color:#888; }
    .footer td:last-child { text-align:right; }
</style>
</head>
<body>

<!-- Header -->
<div class="header">
    <table>
        <tr>
            <td>
                <div class="title">PDRIS — Regional Report</div>
                <div class="sub">{{ $region['name'] }} ({{ ucfirst($region['island_under']) }}) &mdash; Department of Science and Technology — Philippines</div>
            </td>
            <td class="meta">
                Generated by: <strong>{{ $generated_by }}</strong><br>
                Date: <strong>{{ $generated }}</strong><br>
                Period: {{ $date_from }} — {{ $date_to }}
            </td>
        </tr>
    </table>
</div>

<!-- User summary cards -->
<div class="section">
    <div class="section-title">Summary</div>
    <table class="cards-table">
        <tr>
            <td><div class="card-box"><div class="num">{{ $user_stats['provinces'] }}</div><div class="lbl">Provinces</div></div></td>
            <td><div class="card-box"><div class="num">{{ $user_stats['provincial_director'] }}</div><div class="lbl">Directors</div></div></td>
            <td><div class="card-box"><div class="num">{{ $user_stats['provincial_admin'] }}</div><div class="lbl">Prov. Admins</div></div></td>
            <td><div class="card-box"><div class="num">{{ $user_stats['employee'] }}</div><div class="lbl">Employees</div></div></td>
            <td><div class="card-box"><div class="num">{{ $user_stats['total'] }}</div><div class="lbl">Total Users</div></div></td>
        </tr>
    </table>
</div>

<!-- Province Overview -->
<div class="section">
    <div class="section-title">Province Overview</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Province</th>
                <th>Category</th>
                <th>Provincial Director</th>
                <th style="text-align:center;">Employees</th>
                <th style="text-align:center;">Admins</th>
                <th style="text-align:center;">Total Users</th>
            </tr>
        </thead>
        <tbody>
            @forelse($province_stats as $i => $p)
            <tr>
                <td>{{ $i + 1 }}</td>
                <td><strong>{{ $p['name'] }}</strong></td>
                <td>{{ $p['category'] ?? '—' }}</td>
                <td>{{ $p['director'] }}</td>
                <td style="text-align:center;"><span class="badge badge-teal">{{ $p['employees'] }}</span></td>
                <td style="text-align:center;"><span class="badge badge-blue">{{ $p['admins'] }}</span></td>
                <td style="text-align:center;"><strong>{{ $p['total_users'] }}</strong></td>
            </tr>
            @empty
            <tr><td colspan="7" style="text-align:center; color:#999;">No provinces found for this region.</td></tr>
            @endforelse
        </tbody>
    </table>
</div>

<!-- Director KPI Rankings -->
<div class="section">
    <div class="section-title">Director KPI Rankings — {{ $director_rankings[0]['year'] ?? '' }}</div>
    <table class="data-table">
        <thead>
            <tr>
                <th style="width:30px;">Rank</th>
                <th>Director</th>
                <th>Province</th>
                <th>Tier</th>
                <th style="text-align:center; width:70px;">Performer</th>
                <th style="text-align:center; width:60px;">Score</th>
                <th style="width:100px;">Progress</th>
            </tr>
        </thead>
        <tbody>
            @forelse($director_rankings as $d)
            @php
                $rate  = $d['total_pct'];
                $cls   = $rate >= 70 ? 'badge-success' : ($rate >= 40 ? 'badge-warning' : 'badge-error');
                $color = $rate >= 70 ? '#2e7d32'       : ($rate >= 40 ? '#f57f17'       : '#c62828');
                $bk    = $d['bucket'];
                $bkCls = match($bk) { 'Top' => 'badge-success', 'Average' => 'badge-warning', 'Under' => 'badge-error', default => 'badge-grey' };
            @endphp
            <tr>
                <td style="text-align:center; font-weight:bold;">{{ $d['tier_rank'] ?? '—' }}</td>
                <td><strong>{{ $d['name'] ?: '—' }}</strong></td>
                <td>{{ $d['province'] }}</td>
                <td>{{ ucfirst($d['tier']) }}</td>
                <td style="text-align:center;"><span class="badge {{ $bkCls }}">{{ $bk ?? '—' }}</span></td>
                <td style="text-align:center;"><span class="badge {{ $cls }}">{{ $rate }}%</span></td>
                <td>
                    <div class="bar-wrap">
                        <div class="bar-fill" style="width:{{ min($rate, 100) }}%; background:{{ $color }};"></div>
                    </div>
                </td>
            </tr>
            @empty
            <tr><td colspan="7" style="text-align:center; color:#999;">No ranking data available.</td></tr>
            @endforelse
        </tbody>
    </table>
</div>

<!-- Activity Log Stats -->
<div class="section">
    <div class="section-title">Activity Log Summary</div>
    <table class="cards-table">
        <tr>
            <td><div class="card-box"><div class="num">{{ $log_stats['login'] }}</div><div class="lbl">Logins</div></div></td>
            <td><div class="card-box"><div class="num">{{ $log_stats['create'] }}</div><div class="lbl">Creates</div></div></td>
            <td><div class="card-box"><div class="num">{{ $log_stats['update'] }}</div><div class="lbl">Updates</div></div></td>
            <td><div class="card-box"><div class="num">{{ $log_stats['delete'] }}</div><div class="lbl">Deletes</div></div></td>
            <td><div class="card-box"><div class="num">{{ $log_stats['generate'] }}</div><div class="lbl">Generates</div></div></td>
            <td><div class="card-box"><div class="num">{{ $log_stats['export'] }}</div><div class="lbl">Exports</div></div></td>
        </tr>
    </table>
</div>

<!-- Recent Logs -->
<div class="section">
    <div class="section-title">Recent Activity</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>User</th>
                <th>Employee ID</th>
                <th>Role</th>
                <th>Action</th>
                <th>Description</th>
                <th>Date & Time</th>
            </tr>
        </thead>
        <tbody>
            @forelse($recent_logs as $log)
            @php
                $tc = match($log['type']) {
                    'login','logout' => 'badge-success',
                    'create'         => 'badge-blue',
                    'update'         => 'badge-blue',
                    'delete'         => 'badge-error',
                    'generate'       => 'badge-teal',
                    'export'         => 'badge-purple',
                    default          => 'badge-grey',
                };
            @endphp
            <tr>
                <td><strong>{{ $log['name'] ?: '—' }}</strong></td>
                <td>{{ $log['employee_id'] }}</td>
                <td>{{ str_replace('_', ' ', ucfirst($log['role'])) }}</td>
                <td><span class="badge {{ $tc }}">{{ $log['type'] }}</span></td>
                <td>{{ $log['description'] }}</td>
                <td>{{ $log['created_at'] }}</td>
            </tr>
            @empty
            <tr><td colspan="6" style="text-align:center; color:#999;">No recent activity.</td></tr>
            @endforelse
        </tbody>
    </table>
</div>

<!-- Footer -->
<div class="footer">
    <table>
        <tr>
            <td>PDRIS — Provincial Director Ranking Information System</td>
            <td>CONFIDENTIAL — For internal use only</td>
        </tr>
    </table>
</div>

</body>
</html>
